import { access, readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { type ActionManifest, readYaml, root, sortedKeys } from "./support.js";

const actionContracts = [
	{
		directory: "actions/publication/reconcile-assets",
		inputs: [
			"github-token",
			"google-credentials",
			"google-drive-meetup-folder-id",
			"google-drive-meetup-template-folder-id",
			"issue-number",
			"managed-comment-author",
			"mode",
		],
		outputs: ["asset-url", "diagnostics", "drive-files", "result"],
	},
	{
		directory: "actions/event/reconcile",
		inputs: ["github-token", "issue-number", "managed-comment-author", "mode"],
		outputs: ["diagnostics", "is-ready", "result", "state"],
	},
	{
		directory: "actions/event/list-active",
		inputs: ["github-token"],
		outputs: ["diagnostics", "issue-numbers", "result"],
	},
	{
		directory: "actions/referential/validate",
		inputs: [],
		outputs: [
			"diagnostics",
			"host-count",
			"is-valid",
			"result",
			"speaker-count",
		],
	},
	{
		directory: "actions/referential/sync-issue-form",
		inputs: ["mode"],
		outputs: ["changed", "changed-files", "diagnostics", "result"],
	},
	{
		directory: "actions/communication/reconcile",
		inputs: [
			"dispatch-authorized",
			"github-token",
			"issue-number",
			"mailings-token",
			"managed-comment-author",
			"mode",
			"slack-token",
		],
		outputs: ["diagnostics", "dispatched-count", "planned-count", "result"],
	},
] as const;

describe("public action contracts", () => {
	it.each(
		actionContracts,
	)("publishes the exact metadata contract and bundle for $directory", async ({
		directory,
		inputs,
		outputs,
	}) => {
		const manifest = await readYaml<ActionManifest>(
			join(directory, "action.yml"),
		);

		expect(manifest.runs).toMatchObject({
			main: "dist/index.js",
			using: "node24",
		});
		expect(sortedKeys(manifest.inputs)).toEqual([...inputs].sort());
		expect(sortedKeys(manifest.outputs)).toEqual([...outputs].sort());
		const readmePath = join(root, directory, "README.md");
		await expect(access(readmePath)).resolves.toBeUndefined();
		expect(await readFile(readmePath, "utf8")).toContain(
			"This documentation was automatically generated by [CI Dokumentor]",
		);
		await expect(
			access(join(root, directory, "dist/index.js")),
		).resolves.toBeUndefined();
	});

	it("keeps managed-author and dispatch authorization fail-closed", async () => {
		const event = await readYaml<ActionManifest>(
			"actions/event/reconcile/action.yml",
		);
		const communication = await readYaml<ActionManifest>(
			"actions/communication/reconcile/action.yml",
		);

		expect(event.inputs?.["managed-comment-author"]?.required).toBe(true);
		expect(communication.inputs?.["managed-comment-author"]?.required).toBe(
			true,
		);
		expect(communication.inputs?.["dispatch-authorized"]).toMatchObject({
			default: "false",
			required: false,
		});
	});
});
