import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
	type ActionManifest,
	type Job,
	type Step,
	type Workflow,
	automationActionPrefix,
	localWorkflowActionsRef,
	readWorkflow,
	readYaml,
	root,
	sortedKeys,
} from "./support.js";

const publicWorkflowContracts = {
	"check-active-meetup-issues": {
		inputs: [
			"github-app-id",
			"google-drive-meetup-folder-id",
			"google-drive-meetup-template-folder-id",
			"slack-channel-id",
		],
		outputs: ["issue-numbers"],
		secrets: [
			"github-app-private-key",
			"google-credentials",
			"mailings-token",
			"slack-token",
		],
	},
	"update-meetup-issue": {
		inputs: [
			"github-app-id",
			"google-drive-meetup-folder-id",
			"google-drive-meetup-template-folder-id",
			"slack-channel-id",
		],
		outputs: ["communication-diagnostics", "diagnostics", "is-ready", "state"],
		secrets: [
			"github-app-private-key",
			"google-credentials",
			"mailings-token",
			"slack-token",
		],
	},
	"update-meetup-issue-form": {
		inputs: ["github-app-id"],
		outputs: [
			"changed",
			"changed-files",
			"diagnostics",
			"host-count",
			"is-valid",
			"referential-diagnostics",
			"speaker-count",
		],
		secrets: ["github-app-private-key"],
	},
	"check-meetup-referentials-and-issue-form": {
		inputs: [],
		outputs: [
			"host-count",
			"is-valid",
			"issue-form-changed",
			"issue-form-changed-files",
			"issue-form-diagnostics",
			"referential-diagnostics",
			"speaker-count",
		],
		secrets: [],
	},
} as const;

const expectedActionWiring = {
	"check-active-meetup-issues": {
		audit: [
			"publication/reconcile-assets",
			"event/reconcile",
			"communication/reconcile",
		],
		list: ["event/list-active"],
	},
	"update-meetup-issue": {
		manage: [
			"communication/reconcile",
			"publication/reconcile-assets",
			"event/reconcile",
		],
	},
	"update-meetup-issue-form": {
		synchronize: ["referential/validate", "referential/sync-issue-form"],
	},
	"check-meetup-referentials-and-issue-form": {
		validate: ["referential/validate", "referential/sync-issue-form"],
	},
} as const;

describe("public reusable workflow contracts", () => {
	it.each(
		Object.entries(publicWorkflowContracts),
	)("publishes the exact caller contract and generated documentation for %s", async (name, expected) => {
		const workflow = await readWorkflow(name);
		const contract = workflow.on?.workflow_call;
		const documentation = await readFile(
			join(root, `.github/workflows/${name}.md`),
			"utf8",
		);

		expect(workflow.permissions).toEqual({});
		expect(sortedKeys(contract?.inputs)).toEqual([...expected.inputs].sort());
		expect(sortedKeys(contract?.secrets)).toEqual([...expected.secrets].sort());
		expect(sortedKeys(contract?.outputs)).toEqual([...expected.outputs].sort());
		expect(documentation).toContain(
			`GitHub Reusable Workflow: ${workflow.name}`,
		);
		expect(documentation).toContain(
			"This documentation was automatically generated by [CI Dokumentor]",
		);
	});

	it("loads every brain action from the reusable workflow revision", async () => {
		for (const [workflowName, jobs] of Object.entries(expectedActionWiring)) {
			const workflow = await readWorkflow(workflowName);
			for (const [jobName, expectedActions] of Object.entries(jobs)) {
				const actionNames = expectedActions as readonly string[];
				const job = workflow.jobs?.[jobName];
				expect(job, `${workflowName}/${jobName}`).toBeDefined();
				const actionSteps = (job?.steps ?? []).filter((step: Step) =>
					step.uses?.startsWith(automationActionPrefix),
				);
				expect(actionSteps.map((step: Step) => step.uses)).toEqual(
					actionNames.map((action) => `${automationActionPrefix}${action}`),
				);

				const workflowSourceIndex = (job?.steps ?? []).findIndex(
					(step: Step) =>
						step.id === "local-workflow-actions" &&
						step.uses === localWorkflowActionsRef &&
						step.with?.["actions-path"] === "actions",
				);
				const firstActionIndex = (job?.steps ?? []).indexOf(actionSteps[0]);
				expect(
					workflowSourceIndex,
					`${workflowName}/${jobName} local workflow actions loader`,
				).toBeGreaterThanOrEqual(0);
				expect(workflowSourceIndex).toBeLessThan(firstActionIndex);
			}
		}
	});

	it("pins every external workflow dependency to a full commit SHA", async () => {
		const workflowFiles = (
			await readdir(join(root, ".github/workflows"))
		).filter((name) => name.endsWith(".yml"));
		const externalUses: string[] = [];
		for (const file of workflowFiles) {
			const workflow = await readYaml<Workflow>(`.github/workflows/${file}`);
			for (const job of Object.values(workflow.jobs ?? {}) as Job[]) {
				if (job.uses && !job.uses.startsWith("./")) externalUses.push(job.uses);
				for (const step of job.steps ?? []) {
					if (step.uses && !step.uses.startsWith("./")) {
						externalUses.push(step.uses);
					}
				}
			}
		}
		for (const action of [
			"actions/publication/reconcile-assets",
			"actions/event/reconcile",
			"actions/event/list-active",
			"actions/referential/validate",
			"actions/referential/sync-issue-form",
			"actions/communication/reconcile",
		]) {
			const manifest = await readYaml<ActionManifest>(
				join(action, "action.yml"),
			);
			for (const step of manifest.runs?.steps ?? []) {
				if (step.uses && !step.uses.startsWith("./"))
					externalUses.push(step.uses);
			}
		}

		expect(externalUses.length).toBeGreaterThan(0);
		for (const uses of externalUses) {
			expect(uses).toMatch(/^[^@\s]+@[0-9a-f]{40}$/);
		}
	});
});
