import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
	type ActionManifest,
	automationActionPrefix,
	type Job,
	localWorkflowActionsRef,
	readWorkflow,
	readYaml,
	root,
	type Step,
	sortedKeys,
	type Workflow,
	workflowExpression,
} from "./support.js";

const publicWorkflowContracts = {
	"check-active-meetup-issues": {
		inputs: [
			"github-app-id",
			"google-drive-meetup-folder-id",
			"google-drive-meetup-template-folder-id",
			"slack-channel-id",
		],
		outputs: ["issue-numbers"],
		secrets: [
			"github-app-private-key",
			"google-credentials",
			"mailings-token",
			"slack-token",
		],
	},
	"update-meetup-issue": {
		inputs: [
			"github-app-id",
			"google-drive-meetup-folder-id",
			"google-drive-meetup-template-folder-id",
			"slack-channel-id",
		],
		outputs: ["communication-diagnostics", "diagnostics", "is-ready", "state"],
		secrets: [
			"github-app-private-key",
			"google-credentials",
			"mailings-token",
			"slack-token",
		],
	},
	"update-meetup-issue-form": {
		inputs: ["github-app-id"],
		outputs: [
			"changed",
			"changed-files",
			"diagnostics",
			"host-count",
			"is-valid",
			"referential-diagnostics",
			"speaker-count",
		],
		secrets: ["github-app-private-key"],
	},
	"check-meetup-referentials-and-issue-form": {
		inputs: [],
		outputs: [
			"host-count",
			"is-valid",
			"issue-form-changed",
			"issue-form-changed-files",
			"issue-form-diagnostics",
			"referential-diagnostics",
			"speaker-count",
		],
		secrets: [],
	},
} as const;

const expectedActionWiring = {
	"check-active-meetup-issues": {
		audit: [
			"publication/reconcile-assets",
			"event/reconcile",
			"communication/reconcile",
		],
		list: ["event/list-active"],
	},
	"update-meetup-issue": {
		manage: [
			"communication/reconcile",
			"publication/reconcile-assets",
			"event/reconcile",
		],
	},
	"update-meetup-issue-form": {
		synchronize: ["referential/validate", "referential/sync-issue-form"],
	},
	"check-meetup-referentials-and-issue-form": {
		validate: ["referential/validate", "referential/sync-issue-form"],
	},
} as const;

describe("public reusable workflow contracts", () => {
	it.each(Object.entries(publicWorkflowContracts))(
		"publishes the exact caller contract and generated documentation for %s",
		async (name, expected) => {
			// Arrange
			const workflow = await readWorkflow(name);
			const contract = workflow.on?.workflow_call;
			const documentation = await readFile(
				join(root, `.github/workflows/${name}.md`),
				"utf8",
			);

			// Act
			const actual = sortedKeys(contract?.inputs);
			const actual1 = sortedKeys(contract?.secrets);
			const actual2 = sortedKeys(contract?.outputs);

			// Assert
			expect(workflow.permissions).toEqual({});
			expect(actual).toEqual([...expected.inputs, "locale"].sort());
			expect(actual1).toEqual([...expected.secrets].sort());
			expect(actual2).toEqual([...expected.outputs].sort());
			expect(documentation).toContain(
				`GitHub Reusable Workflow: ${workflow.name}`,
			);
			expect(documentation).toContain(
				"This documentation was automatically generated by [CI Dokumentor]",
			);
		},
	);

	it.each(["check-active-meetup-issues", "update-meetup-issue"])(
		"requires and forwards communication tokens and routing in %s",
		async (workflowName) => {
			// Arrange
			const communicationAction = `${automationActionPrefix}communication/reconcile`;

			// Act
			const workflow = await readWorkflow(workflowName);
			const secrets = workflow.on?.workflow_call?.secrets;
			const slackChannel =
				workflow.on?.workflow_call?.inputs?.["slack-channel-id"];
			const communicationSteps = Object.values(workflow.jobs ?? {})
				.flatMap((job) => job.steps ?? [])
				.filter((step) => step.uses === communicationAction);

			// Assert
			expect(secrets?.["mailings-token"]?.required).toBe(true);
			expect(secrets?.["slack-token"]?.required).toBe(true);
			expect(slackChannel?.required).toBe(true);
			expect(slackChannel?.default).toBeUndefined();
			expect(communicationSteps).toHaveLength(1);
			expect(communicationSteps[0].with).toMatchObject({
				"mailings-token": workflowExpression("secrets.mailings-token"),
				"slack-token": workflowExpression("secrets.slack-token"),
				"slack-channel-id": workflowExpression("inputs.slack-channel-id"),
			});
			expect(communicationSteps[0].env).toBeUndefined();
		},
	);

	it.each(Object.entries(expectedActionWiring))(
		"loads actions from the reusable workflow revision in %s",
		async (workflowName, jobs) => {
			// Arrange
			const expectedJobs = Object.entries(jobs);

			// Act
			const workflow = await readWorkflow(workflowName);
			const wiring = expectedJobs.map(([jobName, expectedActions]) => {
				const actionNames = expectedActions as readonly string[];
				const job = workflow.jobs?.[jobName];
				const actionSteps = (job?.steps ?? []).filter((step: Step) =>
					step.uses?.startsWith(automationActionPrefix),
				);
				const workflowSourceIndex = (job?.steps ?? []).findIndex(
					(step: Step) =>
						step.id === "local-workflow-actions" &&
						step.uses === localWorkflowActionsRef &&
						step.with?.["actions-path"] === "actions",
				);
				const firstActionIndex = (job?.steps ?? []).indexOf(actionSteps[0]);
				return {
					jobName,
					actionNames,
					job,
					actionSteps,
					workflowSourceIndex,
					firstActionIndex,
				};
			});

			// Assert
			for (const {
				jobName,
				actionNames,
				job,
				actionSteps,
				workflowSourceIndex,
				firstActionIndex,
			} of wiring) {
				expect(job, `${workflowName}/${jobName}`).toBeDefined();
				expect(actionSteps.map((step: Step) => step.uses)).toEqual(
					actionNames.map((action) => `${automationActionPrefix}${action}`),
				);
				expect(
					workflowSourceIndex,
					`${workflowName}/${jobName} local workflow actions loader`,
				).toBeGreaterThanOrEqual(0);
				expect(workflowSourceIndex).toBeLessThan(firstActionIndex);
			}
		},
	);

	it.each([
		["check-meetup-referentials-and-issue-form", "validate", "check", "false"],
		["update-meetup-issue-form", "synchronize", "fix", undefined],
	] as const)(
		"lets referential actions enforce the configured drift policy in %s",
		async (workflowName, jobName, mode, failOnDrift) => {
			// Arrange
			const workflow = await readWorkflow(workflowName);

			// Act
			const job = workflow.jobs?.[jobName];
			const actions = (job?.steps ?? []).filter((step) =>
				step.uses?.startsWith(`${automationActionPrefix}referential/`),
			);

			// Assert
			expect(job).not.toHaveProperty("continue-on-error");
			expect(actions).toHaveLength(2);
			for (const action of actions) {
				expect(action).not.toHaveProperty("continue-on-error");
				expect(action.if).toBeUndefined();
			}
			expect(actions[1].with?.mode).toBe(mode);
			expect(actions[1].with?.["fail-on-drift"]).toBe(failOnDrift);
		},
	);

	it("pins every external workflow dependency to a full commit SHA", async () => {
		// Arrange
		const workflowFiles = (
			await readdir(join(root, ".github/workflows"))
		).filter((name) => name.endsWith(".yml"));
		const externalUses: string[] = [];

		// Act
		for (const file of workflowFiles) {
			const workflow = await readYaml<Workflow>(`.github/workflows/${file}`);
			for (const job of Object.values(workflow.jobs ?? {}) as Job[]) {
				if (job.uses && !job.uses.startsWith("./")) externalUses.push(job.uses);
				for (const step of job.steps ?? []) {
					if (step.uses && !step.uses.startsWith("./")) {
						externalUses.push(step.uses);
					}
				}
			}
		}
		for (const action of [
			"actions/publication/reconcile-assets",
			"actions/event/reconcile",
			"actions/event/list-active",
			"actions/referential/validate",
			"actions/referential/sync-issue-form",
			"actions/communication/reconcile",
		]) {
			const manifest = await readYaml<ActionManifest>(
				join(action, "action.yml"),
			);
			for (const step of manifest.runs?.steps ?? []) {
				if (step.uses && !step.uses.startsWith("./"))
					externalUses.push(step.uses);
			}
		}

		// Assert
		expect(externalUses.length).toBeGreaterThan(0);
		for (const uses of externalUses) {
			expect(uses).toMatch(/^[^@\s]+@[0-9a-f]{40}$/);
		}
	});
});
